import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'models/ejercicio.dart';
import 'models/rutina.dart';
import 'models/sesion.dart';
import 'screens/main_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();

  // Register Adapters
  // These adapters are generated by running: flutter pub run build_runner build
  Hive.registerAdapter(EjercicioAdapter());
  Hive.registerAdapter(RutinaAdapter());
  Hive.registerAdapter(SesionAdapter());

  // Open Boxes
  await Hive.openBox<Rutina>('rutinas');
  await Hive.openBox<Sesion>('sesiones');

  await initializeDateFormatting('es_ES', null);

  runApp(const JuanTrainingApp());
}

class JuanTrainingApp extends StatelessWidget {
  const JuanTrainingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Juan Training',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
        // Dark theme is popular for fitness apps
        brightness: Brightness.dark,
      ),
      home: const MainScreen(),
    );
  }
}
